name: Build
on: [push, pull_request]

jobs:
    build:
      runs-on: ${{ matrix.os }}
  
      strategy:
        matrix:
          os: [macos-latest, ubuntu-latest, windows-latest]
  
      steps:
      - uses: actions/checkout@v2       
      - uses: actions/setup-node@master
        with:
          node-version: 20
      - name: install dependencies
        run: npm ci
      - name: make
        run: npm run make