name: Release
on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: |
          yarn global add eslint
          yarn lint

      - name: Make
        run: |
          if not startsWith(github.ref, 'refs/tags/') (
            npm run make
          ) 
          else (
            echo "Tag push detected. Skipping make."
          )

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if startsWith(github.ref, 'refs/tags/') (
            npm run publish
          ) 
          else (
            echo "Not a tag push. Skipping publish."
          )