name: Release
on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: |
          yarn global add eslint
          yarn lint

          - name: Make
          run: |
            [ "${{ startsWith(github.ref, 'refs/tags/') }}" != "true" ] && npm run make || true
  
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          [ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ] && npm run publish || true